version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop-hive-combined.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    hostname: datanode
    restart: always
    ports:
      - 9864:9864
      - 9866:9866
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - hadoop-hive-combined.env
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - hadoop-hive-combined.env
  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - hadoop-hive-combined.env

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - hadoop-hive-combined.env
  hive-server:
    container_name: hive-server
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - hadoop-hive-combined.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
  hive-metastore:
    container_name: hive-metastore
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - hadoop-hive-combined.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
  hive-metastore-postgresql:
    container_name: hive-metastore-postgresql
    image: bde2020/hive-metastore-postgresql:3.1.0

  spark-master:
    image: bde2020/spark-master:3.2.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.2.1-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  ml-service:
    image: ml-service
    container_name: ml-service
    ports:
      - 8789:8789

  spark-job:
    image: spark-job
    container_name: spark-job
    depends_on:
      - spark-master
      - spark-worker-1
      - ml-service
    environment:
      SPARK_MASTER_NAME: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_APPLICATION_ARGS: hdfs://namenode:9000/data/users hdfs://namenode:9000/data/categories hdfs://namenode:9000/data/movies hdfs://namenode:9000/data/logs hdfs://namenode:9000/data/error_logs hdfs://namenode:9000/data/reviews http://ml-service:8789/sentiment

  camel-integration:
    container_name: camel-integration
    image: camel-integration
    depends_on:
      - namenode
    volumes:
      - camel_file_location:/log_location/
    ports:
      - "18787:8788"
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8788
      LOG_PATH: "file:/log_location/"
      HDFS_OPTIONS: "?replication=1&append=true"
      HDFS_PATH: "hdfs://namenode:9000/data/"
      HDFS_COMPLETION_SIZE: 10000
      KAFKA_USER_TOPIC_URL: "kafka:user?brokers=host.docker.internal:29092"
      HDFS_USER_URL: "hdfs://namenode:9000/data/"
      HDFS_USER_OPTIONS: "?replication=1&append=true"
      KAFKA_MOVIE_TOPIC_URL: "kafka:movie?brokers=host.docker.internal:29092"
      HDFS_MOVIE_URL: "hdfs://namenode:9000/data/"
      HDFS_MOVIE_OPTIONS: "?replication=1&append=true"
      KAFKA_CATEGORY_TOPIC_URL: "kafka:category?brokers=host.docker.internal:29092"
      HDFS_CATEGORY_URL: "hdfs://namenode:9000/data/"
      HDFS_CATEGORY_OPTIONS: "?replication=1&append=true"
      SERVICE_PRECONDITION: "namenode:9870"

  test-data-gen:
    container_name: test-data-generator
    image: test-data-generator
    volumes:
      - camel_file_location:/logs/
    ports:
      - "8787:8787"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  camel_file_location: